[plugin-info]
SHORT_PLUGIN_NAME = 'pymodaq_plugins_bronkhorst'  

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_template' #to modify
description = 'Plugin to interface Bronkhorst instruments to PyMoDaq'

author = 'Jonas Elmroth Nordlander'
author-email = 'jonas.elmroth_nordlander@chemeng.lth.se'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0']

[build-system]
requires= ["hatchling"]
build-backend= "hatchling.build"

[project]
name="pymodaq_plugins_bronkhorst"
readme=README.rst
classifiers = [
	"Programming Language :: Python :: 3,
	"License :: OSI Approved :: MIT License", 
	"Operating System :: OS Independent", 
]

